### PR TITLE
fix database error detection

### PR DESCRIPTION
**Pull request by karolba**
that didn't work

### CODE REVIEW

**Comment by cvuser0** [comment]
http://boards.4chan.org/g/thread/52819314#p52820355

**Comment by karolba** [comment]
@cvuser0 Well, yes, that's my post.

**Comment by cvuser0** [comment]
@karolba just to make it easier for OP to know who's who and in case you lost your post :^)

**Comment by karolba** [comment]
Took just under 1 hour to press a button!

**Pull request closed without merging**
